version: '3.9'

networks:
  app-network-public:
    driver: bridge

volumes:
  mysql-data:
    driver: local

services:
  db:
    image: mysql:5.7
    container_name: db-mysql
    networks:
      - app-network-public
    restart: always
    env_file: 
      mysql.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - /c/docker/shared:/usr/shared